// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for AbPeersQueryRequestTagMode.
const (
	AbPeersQueryRequestTagModeIntersection AbPeersQueryRequestTagMode = "intersection"
	AbPeersQueryRequestTagModeUnion        AbPeersQueryRequestTagMode = "union"
)

// Defines values for AbRuleRule.
const (
	AbRuleRuleN1 AbRuleRule = 1
	AbRuleRuleN2 AbRuleRule = 2
	AbRuleRuleN3 AbRuleRule = 3
)

// Defines values for AbRuleUpdateRequestRule.
const (
	AbRuleUpdateRequestRuleN1 AbRuleUpdateRequestRule = 1
	AbRuleUpdateRequestRuleN2 AbRuleUpdateRequestRule = 2
	AbRuleUpdateRequestRuleN3 AbRuleUpdateRequestRule = 3
)

// Defines values for AbRuleUpsertRequestRule.
const (
	AbRuleUpsertRequestRuleN1 AbRuleUpsertRequestRule = 1
	AbRuleUpsertRequestRuleN2 AbRuleUpsertRequestRule = 2
	AbRuleUpsertRequestRuleN3 AbRuleUpsertRequestRule = 3
)

// Defines values for AbSettingsMaxPeerOneAb.
const (
	AbSettingsMaxPeerOneAbN0 AbSettingsMaxPeerOneAb = 0
)

// Defines values for AssignRequestTargetType.
const (
	AssignRequestTargetTypeDevice      AssignRequestTargetType = "device"
	AssignRequestTargetTypeDeviceGroup AssignRequestTargetType = "device_group"
	AssignRequestTargetTypeUser        AssignRequestTargetType = "user"
)

// Defines values for AssignmentDtoScopeType.
const (
	AssignmentDtoScopeTypeDeviceGroup AssignmentDtoScopeType = "device_group"
	AssignmentDtoScopeTypeGlobal      AssignmentDtoScopeType = "global"
)

// Defines values for BatchStatusRequestStatus.
const (
	BatchStatusRequestStatusMinus1 BatchStatusRequestStatus = -1
	BatchStatusRequestStatusN0     BatchStatusRequestStatus = 0
	BatchStatusRequestStatusN1     BatchStatusRequestStatus = 1
)

// Defines values for ConsoleAuditRowResult.
const (
	ConsoleAuditRowResultAllowed ConsoleAuditRowResult = "allowed"
	ConsoleAuditRowResultDenied  ConsoleAuditRowResult = "denied"
)

// Defines values for DeviceStatusUpdateRequestStatus.
const (
	Disabled DeviceStatusUpdateRequestStatus = "disabled"
	Enabled  DeviceStatusUpdateRequestStatus = "enabled"
)

// Defines values for EligibilityRowReasonCode.
const (
	Eligible         EligibilityRowReasonCode = "eligible"
	ProtectedRole    EligibilityRowReasonCode = "protected_role"
	SelfTarget       EligibilityRowReasonCode = "self_target"
	SuperAdminTarget EligibilityRowReasonCode = "super_admin_target"
	TargetProtected  EligibilityRowReasonCode = "target_protected"
)

// Defines values for FileAuditReportType.
const (
	FileAuditReportTypeN0 FileAuditReportType = 0
	FileAuditReportTypeN1 FileAuditReportType = 1
)

// Defines values for LoginRequestType.
const (
	LoginRequestTypeAccount   LoginRequestType = "account"
	LoginRequestTypeEmailCode LoginRequestType = "email_code"
	LoginRequestTypeSmsCode   LoginRequestType = "sms_code"
	LoginRequestTypeTfaCode   LoginRequestType = "tfa_code"
)

// Defines values for LoginResponseTfaType.
const (
	PasskeyCheck LoginResponseTfaType = "passkey_check"
	TfaCheck     LoginResponseTfaType = "tfa_check"
)

// Defines values for LoginResponseType.
const (
	LoginResponseTypeAccount    LoginResponseType = "account"
	LoginResponseTypeEmailCheck LoginResponseType = "email_check"
)

// Defines values for NexusBuildViewStatus.
const (
	Building  NexusBuildViewStatus = "building"
	Cancelled NexusBuildViewStatus = "cancelled"
	Completed NexusBuildViewStatus = "completed"
	Failed    NexusBuildViewStatus = "failed"
	Pending   NexusBuildViewStatus = "pending"
)

// Defines values for NexusGenerateDtoArch.
const (
	Aarch64 NexusGenerateDtoArch = "aarch64"
	X86     NexusGenerateDtoArch = "x86"
	X8664   NexusGenerateDtoArch = "x86_64"
)

// Defines values for NexusGenerateDtoOs.
const (
	Windows NexusGenerateDtoOs = "windows"
)

// Defines values for OidcProviderDtoType.
const (
	OidcProviderDtoTypeOauth2 OidcProviderDtoType = "oauth2"
	OidcProviderDtoTypeOidc   OidcProviderDtoType = "oidc"
)

// Defines values for OidcProviderUpsertType.
const (
	OidcProviderUpsertTypeOauth2 OidcProviderUpsertType = "oauth2"
	OidcProviderUpsertTypeOidc   OidcProviderUpsertType = "oidc"
)

// Defines values for PermissionDefinitionScope.
const (
	PermissionDefinitionScopeDeviceGroup PermissionDefinitionScope = "device_group"
	PermissionDefinitionScopeGlobal      PermissionDefinitionScope = "global"
)

// Defines values for ReplaceRolesRequestAssignmentsScopeType.
const (
	ReplaceRolesRequestAssignmentsScopeTypeDeviceGroup ReplaceRolesRequestAssignmentsScopeType = "device_group"
	ReplaceRolesRequestAssignmentsScopeTypeGlobal      ReplaceRolesRequestAssignmentsScopeType = "global"
)

// Defines values for SharedBookRowRule.
const (
	SharedBookRowRuleN1 SharedBookRowRule = 1
	SharedBookRowRuleN2 SharedBookRowRule = 2
	SharedBookRowRuleN3 SharedBookRowRule = 3
)

// Defines values for UpdateUserRequestStatus.
const (
	UpdateUserRequestStatusMinus1 UpdateUserRequestStatus = -1
	UpdateUserRequestStatusN0     UpdateUserRequestStatus = 0
	UpdateUserRequestStatusN1     UpdateUserRequestStatus = 1
)

// Defines values for UserRolesResultEffectiveScope.
const (
	UserRolesResultEffectiveScopeDeviceGroup UserRolesResultEffectiveScope = "device_group"
	UserRolesResultEffectiveScopeGlobal      UserRolesResultEffectiveScope = "global"
	UserRolesResultEffectiveScopeNone        UserRolesResultEffectiveScope = "none"
)

// Defines values for ListAddressBookPeersParamsTagMode.
const (
	ListAddressBookPeersParamsTagModeIntersection ListAddressBookPeersParamsTagMode = "intersection"
	ListAddressBookPeersParamsTagModeUnion        ListAddressBookPeersParamsTagMode = "union"
)

// Defines values for ListAdminUsersParamsIsAdmin.
const (
	ListAdminUsersParamsIsAdminN0 ListAdminUsersParamsIsAdmin = "0"
	ListAdminUsersParamsIsAdminN1 ListAdminUsersParamsIsAdmin = "1"
)

// Defines values for ListConsoleAuditsParamsResult.
const (
	ListConsoleAuditsParamsResultAllowed ListConsoleAuditsParamsResult = "allowed"
	ListConsoleAuditsParamsResultDenied  ListConsoleAuditsParamsResult = "denied"
)

// Defines values for GetDashboardTrendsParamsRange.
const (
	N30d GetDashboardTrendsParamsRange = "30d"
	N7d  GetDashboardTrendsParamsRange = "7d"
	N90d GetDashboardTrendsParamsRange = "90d"
)

// Defines values for ListDevicesParamsStatus.
const (
	ListDevicesParamsStatusN0 ListDevicesParamsStatus = "0"
	ListDevicesParamsStatusN1 ListDevicesParamsStatus = "1"
)

// Defines values for ListDevicesParamsIsOnline.
const (
	ListDevicesParamsIsOnlineN0 ListDevicesParamsIsOnline = "0"
	ListDevicesParamsIsOnlineN1 ListDevicesParamsIsOnline = "1"
)

// Defines values for ListPeersParamsStatus.
const (
	ListPeersParamsStatusN0 ListPeersParamsStatus = "0"
	ListPeersParamsStatusN1 ListPeersParamsStatus = "1"
)

// Defines values for ListPeersParamsIsOnline.
const (
	N0 ListPeersParamsIsOnline = "0"
	N1 ListPeersParamsIsOnline = "1"
)

// Defines values for GetServerServiceConfigParamsService.
const (
	GetServerServiceConfigParamsServiceHbbr GetServerServiceConfigParamsService = "hbbr"
	GetServerServiceConfigParamsServiceHbbs GetServerServiceConfigParamsService = "hbbs"
)

// Defines values for UpdateServerServiceConfigParamsService.
const (
	UpdateServerServiceConfigParamsServiceHbbr UpdateServerServiceConfigParamsService = "hbbr"
	UpdateServerServiceConfigParamsServiceHbbs UpdateServerServiceConfigParamsService = "hbbs"
)

// Defines values for GetServerServiceLogsParamsService.
const (
	GetServerServiceLogsParamsServiceHbbr GetServerServiceLogsParamsService = "hbbr"
	GetServerServiceLogsParamsServiceHbbs GetServerServiceLogsParamsService = "hbbs"
)

// Defines values for RunServerServiceActionParamsService.
const (
	RunServerServiceActionParamsServiceHbbr RunServerServiceActionParamsService = "hbbr"
	RunServerServiceActionParamsServiceHbbs RunServerServiceActionParamsService = "hbbs"
)

// Defines values for RunServerServiceActionParamsAction.
const (
	Apply   RunServerServiceActionParamsAction = "apply"
	Restart RunServerServiceActionParamsAction = "restart"
	Start   RunServerServiceActionParamsAction = "start"
	Stop    RunServerServiceActionParamsAction = "stop"
)

// Defines values for StrategyTargetCandidatesParamsTargetType.
const (
	Device StrategyTargetCandidatesParamsTargetType = "device"
	User   StrategyTargetCandidatesParamsTargetType = "user"
)

// Defines values for StrategyAssignmentsParamsTargetType.
const (
	StrategyAssignmentsParamsTargetTypeDevice      StrategyAssignmentsParamsTargetType = "device"
	StrategyAssignmentsParamsTargetTypeDeviceGroup StrategyAssignmentsParamsTargetType = "device_group"
	StrategyAssignmentsParamsTargetTypeUser        StrategyAssignmentsParamsTargetType = "user"
)

// AbPeer 地址簿 peer 行（findOrCreatePeer 自动建）。
type AbPeer struct {
	AddressBookGuid *string  `json:"address_book_guid,omitempty"`
	Alias           *string  `json:"alias,omitempty"`
	DeviceId        string   `json:"device_id"`
	Guid            string   `json:"guid"`
	Hash            *string  `json:"hash,omitempty"`
	Note            *string  `json:"note,omitempty"`
	Password        *string  `json:"password,omitempty"`
	Tags            []string `json:"tags"`
}

// AbPeerList defines model for AbPeerList.
type AbPeerList struct {
	Data  []AbPeer `json:"data"`
	Total int      `json:"total"`
}

// AbPeerUpsertRequest 新增/更新 peer（客户端兼容字段 username/hostname/platform 等保留解析部分忽略）； PUT 时 tags 全量替换。
type AbPeerUpsertRequest struct {
	Alias    *string   `json:"alias,omitempty"`
	Hash     *string   `json:"hash,omitempty"`
	Id       string    `json:"id"`
	Note     *string   `json:"note,omitempty"`
	Password *string   `json:"password,omitempty"`
	Tags     *[]string `json:"tags,omitempty"`
}

// AbPeersQueryRequest POST peers 查询（ab 必填；tags 过滤 union/intersection 两模式）。
type AbPeersQueryRequest struct {
	Ab      string                      `json:"ab"`
	Alias   *string                     `json:"alias,omitempty"`
	Id      *string                     `json:"id,omitempty"`
	TagMode *AbPeersQueryRequestTagMode `json:"tag_mode,omitempty"`
	Tags    *[]string                   `json:"tags,omitempty"`
}

// AbPeersQueryRequestTagMode defines model for AbPeersQueryRequest.TagMode.
type AbPeersQueryRequestTagMode string

// AbRule 规则行（targetUserId/targetGroupId 双空=everyone）。
type AbRule struct {
	AddressBookGuid string     `json:"address_book_guid"`
	Guid            string     `json:"guid"`
	Rule            AbRuleRule `json:"rule"`
	TargetGroupId   *string    `json:"target_group_id,omitempty"`
	TargetUserId    *string    `json:"target_user_id,omitempty"`
}

// AbRuleRule defines model for AbRule.Rule.
type AbRuleRule int

// AbRuleList 规则列表（address_books.view）。
type AbRuleList struct {
	Data []AbRule `json:"data"`
}

// AbRuleUpdateRequest 更新规则（guid=规则 guid）。
type AbRuleUpdateRequest struct {
	// Guid 规则 guid
	Guid string                  `json:"guid"`
	Rule AbRuleUpdateRequestRule `json:"rule"`
}

// AbRuleUpdateRequestRule defines model for AbRuleUpdateRequest.Rule.
type AbRuleUpdateRequestRule int

// AbRuleUpsertRequest 建规则（guid=地址簿；user/group 互斥 409；重复 409 This rule already exists）。
type AbRuleUpsertRequest struct {
	// Group 目标组 guid（与 user 互斥）
	Group *string `json:"group,omitempty"`

	// Guid 地址簿 guid
	Guid string                  `json:"guid"`
	Rule AbRuleUpsertRequestRule `json:"rule"`

	// User 目标用户 guid（与 group 互斥）
	User *string `json:"user,omitempty"`
}

// AbRuleUpsertRequestRule defines model for AbRuleUpsertRequest.Rule.
type AbRuleUpsertRequestRule int

// AbSettings 兼容怪癖——恒返回 max_peer_one_ab=0。
type AbSettings struct {
	MaxPeerOneAb AbSettingsMaxPeerOneAb `json:"max_peer_one_ab"`
}

// AbSettingsMaxPeerOneAb defines model for AbSettings.MaxPeerOneAb.
type AbSettingsMaxPeerOneAb int

// AbTag 地址簿标签（color 为 ARGB uint）。
type AbTag struct {
	Color int32  `json:"color"`
	Guid  string `json:"guid"`
	Name  string `json:"name"`
}

// AbTagList 书内标签列表（tag_colors 为 JSON 编码串，客户端硬依赖）。
type AbTagList struct {
	Data      []AbTag `json:"data"`
	TagColors *string `json:"tag_colors,omitempty"`
}

// AbTagRenameRequest defines model for AbTagRenameRequest.
type AbTagRenameRequest struct {
	Name string `json:"name"`
}

// AbTagUpsertRequest 新增标签（同名 409）/更新颜色。
type AbTagUpsertRequest struct {
	Color int32  `json:"color"`
	Name  string `json:"name"`
}

// AbTagsReplaceRequest 全量替换书内标签。
type AbTagsReplaceRequest struct {
	Tags []struct {
		Color int32  `json:"color"`
		Name  string `json:"name"`
	} `json:"tags"`
}

// AccessibleGroupPage defines model for AccessibleGroupPage.
type AccessibleGroupPage struct {
	Data  []AccessibleGroupView `json:"data"`
	Total int                   `json:"total"`
}

// AccessibleGroupView defines model for AccessibleGroupView.
type AccessibleGroupView struct {
	Guid string `json:"guid"`
	Name string `json:"name"`
	Note string `json:"note"`
}

// AddDevicesResult defines model for AddDevicesResult.
type AddDevicesResult struct {
	AddedCount int `json:"added_count"`
}

// AddressBookRef 地址簿引用（personal 幂等取/建）。
type AddressBookRef struct {
	Guid string `json:"guid"`
	Name string `json:"name"`
}

// AdminUserPage 管理员用户分页（10 过滤参数；行含 is_protected/strategy_name/role_names）。
type AdminUserPage struct {
	Data []struct {
		CreatedAt   *time.Time `json:"created_at,omitempty"`
		DisplayName *string    `json:"display_name,omitempty"`
		Email       *string    `json:"email,omitempty"`
		Guid        string     `json:"guid"`

		// IsAdmin admin 行 role_names 追加 'Super Admin'
		IsAdmin       bool     `json:"is_admin"`
		IsProtected   bool     `json:"is_protected"`
		Name          string   `json:"name"`
		Note          *string  `json:"note,omitempty"`
		RoleNames     []string `json:"role_names"`
		Status        int      `json:"status"`
		StrategyName  *string  `json:"strategy_name,omitempty"`
		UserGroupGuid *string  `json:"user_group_guid,omitempty"`
		UserGroupName *string  `json:"user_group_name,omitempty"`
		Username      string   `json:"username"`
	} `json:"data"`
	Total int `json:"total"`
}

// AlarmAuditPage defines model for AlarmAuditPage.
type AlarmAuditPage struct {
	Data  []AlarmAuditRow `json:"data"`
	Total int             `json:"total"`
}

// AlarmAuditReport 告警审计上报（Public + per-IP 50/min；UNIQUE(device_id,nonce) 幂等）。
type AlarmAuditReport struct {
	ConnAuditRef *string `json:"conn_audit_ref,omitempty"`
	ConnId       *string `json:"conn_id,omitempty"`
	Id           string  `json:"id"`

	// Info JSON 字符串原样落库
	Info  string  `json:"info"`
	Nonce *string `json:"nonce,omitempty"`
	Typ   int     `json:"typ"`
	Uuid  string  `json:"uuid"`
}

// AlarmAuditRow defines model for AlarmAuditRow.
type AlarmAuditRow struct {
	ConnAuditRef *string    `json:"conn_audit_ref,omitempty"`
	ConnId       *string    `json:"conn_id,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	DeviceId     string     `json:"device_id"`
	DeviceUuid   string     `json:"device_uuid"`
	Id           int        `json:"id"`
	Info         string     `json:"info"`
	Nonce        *string    `json:"nonce,omitempty"`
	Typ          int        `json:"typ"`
}

// AssignError defines model for AssignError.
type AssignError struct {
	Reason     string `json:"reason"`
	TargetGuid string `json:"target_guid"`
}

// AssignRequest defines model for AssignRequest.
type AssignRequest struct {
	TargetGuids []string                `json:"target_guids"`
	TargetType  AssignRequestTargetType `json:"target_type"`
}

// AssignRequestTargetType defines model for AssignRequest.TargetType.
type AssignRequestTargetType string

// AssignResult defines model for AssignResult.
type AssignResult struct {
	Errors  []AssignError `json:"errors"`
	Success []string      `json:"success"`
}

// AssignmentDto defines model for AssignmentDto.
type AssignmentDto struct {
	DeviceGroupGuids []string               `json:"device_group_guids"`
	RoleGuid         string                 `json:"role_guid"`
	RoleName         string                 `json:"role_name"`
	ScopeType        AssignmentDtoScopeType `json:"scope_type"`
}

// AssignmentDtoScopeType defines model for AssignmentDto.ScopeType.
type AssignmentDtoScopeType string

// AvatarResponse defines model for AvatarResponse.
type AvatarResponse struct {
	Avatar string `json:"avatar"`
}

// BatchResult 批量部分成功结果；操作者快照与库内状态漂移时整批 409。
type BatchResult struct {
	Failed []struct {
		Guid   string `json:"guid"`
		Reason string `json:"reason"`
	} `json:"failed"`
	FailedCount    int      `json:"failedCount"`
	Succeeded      []string `json:"succeeded"`
	SucceededCount int      `json:"succeededCount"`
	Total          int      `json:"total"`
}

// BatchSecurityRequest 批量安全设置（写 users.info JSON；统一撤 token）。
type BatchSecurityRequest struct {
	EmailVerification *bool    `json:"email_verification,omitempty"`
	Guids             []string `json:"guids"`

	// NewPassword 管理员重置口令；不重置已登记 2FA/通行密钥
	NewPassword *string `json:"new_password,omitempty"`
	TfaEnforce  *bool   `json:"tfa_enforce,omitempty"`
}

// BatchSessionsRequest defines model for BatchSessionsRequest.
type BatchSessionsRequest struct {
	Guids []string `json:"guids"`
}

// BatchStatusRequest 批量启停（UNVERIFIED=-1/DISABLED=0/ACTIVE=1）。
type BatchStatusRequest struct {
	Guids  []string                 `json:"guids"`
	Status BatchStatusRequestStatus `json:"status"`
}

// BatchStatusRequestStatus defines model for BatchStatusRequest.Status.
type BatchStatusRequestStatus int

// BookGuidsRequest defines model for BookGuidsRequest.
type BookGuidsRequest struct {
	Guids []string `json:"guids"`
}

// BookPaginationRequest 分页查询（current/pageSize/name/note）。
type BookPaginationRequest struct {
	Current  *int    `json:"current,omitempty"`
	Name     *string `json:"name,omitempty"`
	Note     *string `json:"note,omitempty"`
	PageSize *int    `json:"pageSize,omitempty"`
}

// BuildFiles 构建产物清单（files JSON 落库形态展开）。
type BuildFiles struct {
	Files []struct {
		Filename string `json:"filename"`
		Size     *int   `json:"size,omitempty"`
	} `json:"files"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// ConnActiveList 活跃连接列表（devices.disconnect 权限 + device_group scope 过滤）。
type ConnActiveList struct {
	Data []ConnActiveRow `json:"data"`
}

// ConnActiveRow 活跃连接行（can_disconnect = scope ∩ active）。
type ConnActiveRow struct {
	Action        string     `json:"action"`
	CanDisconnect bool       `json:"can_disconnect"`
	ClosedAt      *time.Time `json:"closed_at,omitempty"`
	ConnId        string     `json:"conn_id"`
	DeviceId      string     `json:"device_id"`
	DeviceUuid    string     `json:"device_uuid"`
	EstablishedAt *time.Time `json:"established_at,omitempty"`
	Id            int        `json:"id"`
	Ip            *string    `json:"ip,omitempty"`
	Note          *string    `json:"note,omitempty"`
	Peer          *[]string  `json:"peer,omitempty"`
	RequestedAt   time.Time  `json:"requested_at"`
	SessionId     *string    `json:"session_id,omitempty"`
	Type          int        `json:"type"`
}

// ConnAuditPage 连接审计分页（audit.view；过滤+分页）。
type ConnAuditPage struct {
	Data  []ConnAuditRow `json:"data"`
	Total int            `json:"total"`
}

// ConnAuditReport 连接审计上报（Public + per-IP 50/min；upsert：按 id+uuid+conn_id 定位， action='new'→'open'、”→'established'）。
type ConnAuditReport struct {
	Action       *string `json:"action,omitempty"`
	ConnAuditRef *string `json:"conn_audit_ref,omitempty"`
	ConnId       *string `json:"conn_id,omitempty"`

	// Id 设备 id
	Id          string    `json:"id"`
	Ip          *string   `json:"ip,omitempty"`
	Nonce       *string   `json:"nonce,omitempty"`
	Note        *string   `json:"note,omitempty"`
	Peer        *[]string `json:"peer,omitempty"`
	PrimaryAuth *int      `json:"primary_auth,omitempty"`
	SessionId   *string   `json:"session_id,omitempty"`
	TwoFactor   *int      `json:"two_factor,omitempty"`
	Type        *int      `json:"type,omitempty"`

	// Uuid 设备 uuid
	Uuid *string `json:"uuid,omitempty"`
}

// ConnAuditRow 连接审计查询行。
type ConnAuditRow struct {
	Action        string     `json:"action"`
	ClosedAt      *time.Time `json:"closed_at,omitempty"`
	ConnAuditRef  *string    `json:"conn_audit_ref,omitempty"`
	ConnId        string     `json:"conn_id"`
	DeviceId      string     `json:"device_id"`
	DeviceUuid    string     `json:"device_uuid"`
	EstablishedAt *time.Time `json:"established_at,omitempty"`
	Id            int        `json:"id"`
	Ip            *string    `json:"ip,omitempty"`
	Nonce         *string    `json:"nonce,omitempty"`
	Note          *string    `json:"note,omitempty"`
	Peer          *[]string  `json:"peer,omitempty"`
	PrimaryAuth   *int       `json:"primary_auth,omitempty"`
	RequestedAt   time.Time  `json:"requested_at"`
	SessionId     *string    `json:"session_id,omitempty"`
	TwoFactor     *int       `json:"two_factor,omitempty"`
	Type          int        `json:"type"`
}

// ConnNoteUpdate 超管改 note（RequireSuperAdmin；仅 note）。
type ConnNoteUpdate struct {
	Note string `json:"note"`
}

// ConsoleAuditPage defines model for ConsoleAuditPage.
type ConsoleAuditPage struct {
	Data  []ConsoleAuditRow `json:"data"`
	Total int               `json:"total"`
}

// ConsoleAuditRow 控制台审计行（M2 rbac 审计表查询端，形状对齐 console_audits 表）： actor_user_name 由 users 表 LEFT JOIN 补齐（系统级动作为 null）； before_state/after_state 以原始 JSON 直出（空/非法为 null）。
type ConsoleAuditRow struct {
	Action        string                `json:"action"`
	ActorUserGuid *string               `json:"actor_user_guid"`
	ActorUserName *string               `json:"actor_user_name"`
	AfterState    interface{}           `json:"after_state,omitempty"`
	BeforeState   interface{}           `json:"before_state,omitempty"`
	CreatedAt     time.Time             `json:"created_at"`
	Guid          string                `json:"guid"`
	Reason        *string               `json:"reason"`
	RequestId     *string               `json:"request_id"`
	Result        ConsoleAuditRowResult `json:"result"`
	TargetGuid    *string               `json:"target_guid,omitempty"`
	TargetType    string                `json:"target_type"`
}

// ConsoleAuditRowResult defines model for ConsoleAuditRow.Result.
type ConsoleAuditRowResult string

// CreateBookProfileRequest 新建地址簿（custom/shared 共用；重名 409 Address book name already exists）。
type CreateBookProfileRequest struct {
	Info *struct {
		Password *string `json:"password,omitempty"`
	} `json:"info,omitempty"`
	Name     string  `json:"name"`
	Note     *string `json:"note,omitempty"`
	Password *string `json:"password,omitempty"`
}

// CreateUserRequest 创建用户（重名 400 Username already exists；bcrypt(10)）。
type CreateUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Note     *string             `json:"note,omitempty"`
	Password string              `json:"password"`

	// UserGroupGuid 携带时需追加 user_groups.membership 条件授权
	UserGroupGuid *string `json:"user_group_guid,omitempty"`
	Username      string  `json:"username"`
}

// DashboardOverview SuperAdmin 仪表盘聚合：devices.online=lastHeartbeat≥now-60s AND status=1； connections.success=establishedAt/closedAt 双非空、failure=closedAt 非空且 establishedAt 空；counts.groups=user_groups+device_groups 合并。
type DashboardOverview struct {
	Connections struct {
		Failure int `json:"failure"`
		Success int `json:"success"`
		Today   int `json:"today"`
	} `json:"connections"`
	Counts struct {
		AddressBooks int `json:"addressBooks"`
		Groups       int `json:"groups"`
		Roles        int `json:"roles"`
		Strategies   int `json:"strategies"`
	} `json:"counts"`
	Devices struct {
		Online int `json:"online"`
		Total  int `json:"total"`
	} `json:"devices"`
	Files struct {
		Today  int `json:"today"`
		Upload int `json:"upload"`
	} `json:"files"`

	// SystemStatus gopsutil cpu/mem/disk/uptime（参考 systeminformation）。
	SystemStatus struct {
		Cpu    float32 `json:"cpu"`
		Disk   float32 `json:"disk"`
		Memory float32 `json:"memory"`
		Uptime int     `json:"uptime"`
	} `json:"systemStatus"`
	Users struct {
		Admin int `json:"admin"`
		Total int `json:"total"`
	} `json:"users"`
}

// DashboardTrends range ∈ 7d|30d|90d 逐日聚合（connection_audits/users(createdAt)/alarm_audits； 空日补 0）。
type DashboardTrends struct {
	AlarmTrend []struct {
		Count int                `json:"count"`
		Date  openapi_types.Date `json:"date"`
	} `json:"alarmTrend"`
	ConnectionTrend []struct {
		Count int                `json:"count"`
		Date  openapi_types.Date `json:"date"`
	} `json:"connectionTrend"`
	NewUserTrend []struct {
		Date     openapi_types.Date `json:"date"`
		NewUsers int                `json:"newUsers"`
	} `json:"newUserTrend"`
}

// DeleteUserGroupResult defines model for DeleteUserGroupResult.
type DeleteUserGroupResult struct {
	// DeletedRuleCount M2 恒 0（address_book_rules 属 M3）
	DeletedRuleCount int `json:"deleted_rule_count"`

	// MovedUserCount 回落默认组的成员数
	MovedUserCount int `json:"moved_user_count"`
}

// DeviceGroupPage defines model for DeviceGroupPage.
type DeviceGroupPage struct {
	Data  []DeviceGroupView `json:"data"`
	Total int               `json:"total"`
}

// DeviceGroupTargetPage defines model for DeviceGroupTargetPage.
type DeviceGroupTargetPage struct {
	Data  []DeviceGroupTargetView `json:"data"`
	Total int                     `json:"total"`
}

// DeviceGroupTargetView defines model for DeviceGroupTargetView.
type DeviceGroupTargetView struct {
	Guid string `json:"guid"`
	Name string `json:"name"`
}

// DeviceGroupUpsertRequest defines model for DeviceGroupUpsertRequest.
type DeviceGroupUpsertRequest struct {
	Name string  `json:"name"`
	Note *string `json:"note,omitempty"`
}

// DeviceGroupView defines model for DeviceGroupView.
type DeviceGroupView struct {
	CreatedAt    time.Time `json:"created_at"`
	DeviceCount  int       `json:"device_count"`
	Guid         string    `json:"guid"`
	Name         string    `json:"name"`
	Note         string    `json:"note"`
	StrategyGuid *string   `json:"strategy_guid"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Name *string `json:"name,omitempty"`
	Os   *string `json:"os,omitempty"`
	Type *string `json:"type,omitempty"`
}

// DevicePage defines model for DevicePage.
type DevicePage struct {
	Data  []DeviceView `json:"data"`
	Total int          `json:"total"`
}

// DeviceStatusUpdateRequest defines model for DeviceStatusUpdateRequest.
type DeviceStatusUpdateRequest struct {
	// Guids peer.uuid 数组
	Guids  []string                        `json:"guids"`
	Status DeviceStatusUpdateRequestStatus `json:"status"`
}

// DeviceStatusUpdateRequestStatus defines model for DeviceStatusUpdateRequest.Status.
type DeviceStatusUpdateRequestStatus string

// DeviceStatusUpdateResult defines model for DeviceStatusUpdateResult.
type DeviceStatusUpdateResult struct {
	Failed         []string `json:"failed"`
	FailedCount    int      `json:"failedCount"`
	Succeeded      []string `json:"succeeded"`
	SucceededCount int      `json:"succeededCount"`
	Total          int      `json:"total"`
}

// DeviceTargetPage defines model for DeviceTargetPage.
type DeviceTargetPage struct {
	Data  []DeviceTargetView `json:"data"`
	Total int                `json:"total"`
}

// DeviceTargetView defines model for DeviceTargetView.
type DeviceTargetView struct {
	Id   string `json:"id"`
	Uuid string `json:"uuid"`
}

// DeviceView defines model for DeviceView.
type DeviceView struct {
	DeviceGroupGuid *string `json:"deviceGroupGuid"`
	DeviceGroupName string  `json:"device_group_name"`

	// Guid = peer.uuid
	Guid string `json:"guid"`

	// Id peer.id（数字设备 ID 字符串）
	Id   string   `json:"id"`
	Info PeerInfo `json:"info"`

	// IsOnline lastHeartbeat > now-60s（60 秒阈值硬编码）
	IsOnline   bool       `json:"is_online"`
	LastOnline *time.Time `json:"last_online"`
	Note       string     `json:"note"`

	// Status 1=正常 / 0=停用
	Status       int    `json:"status"`
	StrategyName string `json:"strategy_name"`

	// User = userGuid 或空串
	User     string  `json:"user"`
	UserGuid *string `json:"userGuid"`
	UserName string  `json:"user_name"`
}

// DisconnectRequest defines model for DisconnectRequest.
type DisconnectRequest struct {
	ConnIds []int `json:"connIds"`
}

// DisconnectResult defines model for DisconnectResult.
type DisconnectResult struct {
	PendingDisconnectCount int `json:"pending_disconnect_count"`
}

// EffectivePermissions defines model for EffectivePermissions.
type EffectivePermissions struct {
	// Permissions 生效码（依赖过滤后）
	Permissions []string `json:"permissions"`
	Scopes      struct {
		// DeviceGroup <设备组guid>: [生效码...]
		DeviceGroup map[string][]string `json:"device_group"`
		Global      []string            `json:"global"`
	} `json:"scopes"`
}

// EligibilityRow defines model for EligibilityRow.
type EligibilityRow struct {
	Eligible         bool                     `json:"eligible"`
	ProtectedAccount bool                     `json:"protected_account"`
	ReasonCode       EligibilityRowReasonCode `json:"reason_code"`
	RoleGuid         string                   `json:"role_guid"`
	RoleName         string                   `json:"role_name"`
}

// EligibilityRowReasonCode defines model for EligibilityRow.ReasonCode.
type EligibilityRowReasonCode string

// Error NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type Error struct {
	Error      string        `json:"error"`
	Message    Error_Message `json:"message"`
	StatusCode int           `json:"statusCode"`
}

// ErrorMessage0 defines model for .
type ErrorMessage0 = string

// ErrorMessage1 defines model for .
type ErrorMessage1 = []string

// ErrorMessage2 defines model for .
type ErrorMessage2 = map[string]interface{}

// Error_Message defines model for Error.Message.
type Error_Message struct {
	union json.RawMessage
}

// FileAuditPage defines model for FileAuditPage.
type FileAuditPage struct {
	Data  []FileAuditRow `json:"data"`
	Total int            `json:"total"`
}

// FileAuditReport 文件审计上报（Public + per-IP 50/min；UNIQUE(device_id,nonce) 幂等）。
type FileAuditReport struct {
	ConnId *string `json:"conn_id,omitempty"`

	// Id 设备 id
	Id string `json:"id"`

	// Info JSON 字符串原样落库
	Info   string  `json:"info"`
	IsFile bool    `json:"is_file"`
	Nonce  *string `json:"nonce,omitempty"`
	Path   *string `json:"path,omitempty"`
	PeerId string  `json:"peer_id"`

	// Type 0=upload / 1=download
	Type FileAuditReportType `json:"type"`

	// Uuid 设备 uuid
	Uuid string `json:"uuid"`
}

// FileAuditReportType 0=upload / 1=download
type FileAuditReportType int

// FileAuditRow defines model for FileAuditRow.
type FileAuditRow struct {
	ClientIp   *string    `json:"client_ip,omitempty"`
	ClientName *string    `json:"client_name,omitempty"`
	ConnId     *string    `json:"conn_id,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	DeviceId   string     `json:"device_id"`
	DeviceUuid string     `json:"device_uuid"`
	FileCount  *int       `json:"file_count,omitempty"`
	Id         int        `json:"id"`
	Info       *string    `json:"info,omitempty"`
	IsFile     bool       `json:"is_file"`
	Nonce      *string    `json:"nonce,omitempty"`
	Path       *string    `json:"path,omitempty"`
	PeerId     string     `json:"peer_id"`
	Type       int        `json:"type"`
}

// FrontendSettings 前端公开设置（Public）。
type FrontendSettings struct {
	DefaultLanguage  string `json:"defaultLanguage"`
	WatermarkEnabled bool   `json:"watermarkEnabled"`
	WebauthnEnabled  bool   `json:"webauthnEnabled"`
}

// GeneralSettings 通用设置嵌套 DTO（无 siteFrontendUrl 时 effectiveFrontendUrl 回退 localhost:3000）。
type GeneralSettings struct {
	AuditRetentionDays int    `json:"auditRetentionDays"`
	DefaultLanguage    string `json:"defaultLanguage"`
	JwtExpiryDays      int    `json:"jwtExpiryDays"`
	Site               struct {
		BackendUrl  string `json:"backendUrl"`
		FrontendUrl string `json:"frontendUrl"`
	} `json:"site"`
	WatermarkEnabled bool `json:"watermarkEnabled"`
	Webauthn         struct {
		Enabled bool   `json:"enabled"`
		RpName  string `json:"rpName"`
	} `json:"webauthn"`
}

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	// Conns 当前活跃连接 ID；键缺失 ≠ 空（指针判空区分）
	Conns *[]int `json:"conns,omitempty"`

	// Id RustDesk 数字设备 ID（如 "123456789"）
	Id string `json:"id"`

	// ModifiedAt 客户端策略版本戳（毫秒 epoch）
	ModifiedAt int64 `json:"modified_at"`

	// Uuid 设备 UUID（peers 主键）
	Uuid string `json:"uuid"`

	// Ver 客户端整版本号（格式化规则见 info.version）
	Ver int `json:"ver"`
}

// HeartbeatResponse defines model for HeartbeatResponse.
type HeartbeatResponse struct {
	// Disconnect 待断连 connId 列表（客户端确认语义）
	Disconnect *[]int `json:"disconnect,omitempty"`

	// ModifiedAt 下发用策略 updatedAt（毫秒）
	ModifiedAt *int64 `json:"modified_at,omitempty"`
	Strategy   *struct {
		ConfigOptions map[string]string `json:"config_options"`
	} `json:"strategy,omitempty"`
}

// InvitationAcceptRequest 接受邀请（bcrypt(10) + status=ACTIVE + usedAt=now）。
type InvitationAcceptRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// InvitationInfo 邀请核对信息（token 无效/已用/过期 → 400 固定文案）。
type InvitationInfo struct {
	// DisplayName 可为空串
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Name        string              `json:"name"`
}

// InvitationTokenRequest defines model for InvitationTokenRequest.
type InvitationTokenRequest struct {
	// Token 64 hex 邀请 token
	Token string `json:"token"`
}

// InviteResult 邮件成功仅 message；失败降级返回 token 明文。
type InviteResult struct {
	Message string `json:"message"`

	// Token 邮件发送失败时的明文回退（成功时不返回）
	Token *string `json:"token,omitempty"`
}

// InviteUserRequest 邀请注册（建 UNVERIFIED 用户 + 7 天邀请 token）。
type InviteUserRequest struct {
	DisplayName   *string             `json:"display_name,omitempty"`
	Email         openapi_types.Email `json:"email"`
	Name          string              `json:"name"`
	Note          *string             `json:"note,omitempty"`
	UserGroupGuid *string             `json:"user_group_guid,omitempty"`
}

// LdapConfig LDAP 配置（bindCredentials 回读掩码 '******'、PUT 命中掩码跳过； test 语义同 smtp 恒 200）。
type LdapConfig struct {
	AdminGroups       *[]string `json:"adminGroups,omitempty"`
	BindCredentials   *string   `json:"bindCredentials,omitempty"`
	BindDN            *string   `json:"bindDN,omitempty"`
	Enabled           *bool     `json:"enabled,omitempty"`
	GroupSearchBase   *string   `json:"groupSearchBase,omitempty"`
	GroupSearchFilter *string   `json:"groupSearchFilter,omitempty"`
	SearchAttributes  *[]string `json:"searchAttributes,omitempty"`
	SearchBase        *string   `json:"searchBase,omitempty"`
	SearchFilter      *string   `json:"searchFilter,omitempty"`
	TlsOptions        *struct {
		Ca         *string `json:"ca,omitempty"`
		Cert       *string `json:"cert,omitempty"`
		Key        *string `json:"key,omitempty"`
		Servername *string `json:"servername,omitempty"`
	} `json:"tlsOptions,omitempty"`
	Urls *[]string `json:"urls,omitempty"`
}

// LegacyAbSaveRequest legacy 全量保存（data 为双重 JSON 编码串；事务全删全插）。
type LegacyAbSaveRequest struct {
	Data string `json:"data"`
}

// LoginRequest type 分支请求；account 需 username/password， tfa_code 需 secret+tfaCode，email_code 需 secret+verificationCode。
type LoginRequest struct {
	AutoLogin  *bool       `json:"autoLogin,omitempty"`
	DeviceInfo *DeviceInfo `json:"deviceInfo,omitempty"`

	// Id 设备 ID
	Id       *string           `json:"id,omitempty"`
	Password *string           `json:"password,omitempty"`
	Secret   *string           `json:"secret,omitempty"`
	TfaCode  *string           `json:"tfaCode,omitempty"`
	Type     *LoginRequestType `json:"type,omitempty"`
	Username *string           `json:"username,omitempty"`

	// Uuid 设备 UUID
	Uuid             *string `json:"uuid,omitempty"`
	VerificationCode *string `json:"verificationCode,omitempty"`
}

// LoginRequestType defines model for LoginRequest.Type.
type LoginRequestType string

// LoginResponse 分支结构：account 带 access_token+user； 两步验证带 type=email_check + tfa_type + secret； passkey_tfa 第一步复用 email_check 类型位并附 passkey_options。
type LoginResponse struct {
	AccessToken    *string                 `json:"access_token,omitempty"`
	PasskeyOptions *map[string]interface{} `json:"passkey_options,omitempty"`
	Secret         *string                 `json:"secret,omitempty"`
	TfaType        *LoginResponseTfaType   `json:"tfa_type,omitempty"`
	Type           LoginResponseType       `json:"type"`

	// User 用户响应 payload（snake_case 契约，禁止规范化）。
	User *UserPayload `json:"user,omitempty"`
}

// LoginResponseTfaType defines model for LoginResponse.TfaType.
type LoginResponseTfaType string

// LoginResponseType defines model for LoginResponse.Type.
type LoginResponseType string

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	Id   *string `json:"id,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
}

// MemberPage defines model for MemberPage.
type MemberPage struct {
	Data  []MemberView `json:"data"`
	Total int          `json:"total"`
}

// MemberView defines model for MemberView.
type MemberView struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
	Guid        string `json:"guid"`
	Username    string `json:"username"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// MoveUsersRequest defines model for MoveUsersRequest.
type MoveUsersRequest struct {
	UserGuids []string `json:"user_guids"`
}

// MoveUsersResult defines model for MoveUsersResult.
type MoveUsersResult struct {
	MovedUserCount int `json:"moved_user_count"`
}

// NexusBindStatus nexus 绑定态（nexus_tokens 行）。
type NexusBindStatus struct {
	Bound         bool       `json:"bound"`
	CurrentUuid   *string    `json:"current_uuid,omitempty"`
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	NexusUsername *string    `json:"nexus_username,omitempty"`
}

// NexusBuildView 构建任务视图（pending→building→completed|failed|cancelled）。
type NexusBuildView struct {
	Arch      string     `json:"arch"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Custom JSON 串
	Custom  *string              `json:"custom,omitempty"`
	Message *string              `json:"message,omitempty"`
	Os      string               `json:"os"`
	Status  NexusBuildViewStatus `json:"status"`
	Uuid    string               `json:"uuid"`
}

// NexusBuildViewStatus defines model for NexusBuildView.Status.
type NexusBuildViewStatus string

// NexusGenerateDto 构建参数（os 仅 windows；custom 键校验归上游）。
type NexusGenerateDto struct {
	Arch NexusGenerateDtoArch `json:"arch"`

	// Custom app-name/password/salt/conn-type/disable-*(Y|N)/override-settings/ default-settings。
	Custom map[string]string  `json:"custom"`
	Os     NexusGenerateDtoOs `json:"os"`
}

// NexusGenerateDtoArch defines model for NexusGenerateDto.Arch.
type NexusGenerateDtoArch string

// NexusGenerateDtoOs defines model for NexusGenerateDto.Os.
type NexusGenerateDtoOs string

// NodeStatus 节点状态（并发 GET /v1/status 握手；不可达返回 reachable:false + services:[]）。
type NodeStatus struct {
	ApiVersion *int     `json:"api_version,omitempty"`
	Error      *string  `json:"error,omitempty"`
	Id         string   `json:"id"`
	Name       string   `json:"name"`
	NodeId     *string  `json:"node_id,omitempty"`
	Reachable  bool     `json:"reachable"`
	Services   []string `json:"services"`
	Version    *string  `json:"version,omitempty"`
}

// OidcAuthRequest defines model for OidcAuthRequest.
type OidcAuthRequest struct {
	DeviceId            *string     `json:"deviceId,omitempty"`
	DeviceInfo          *DeviceInfo `json:"deviceInfo,omitempty"`
	DeviceUuid          *string     `json:"deviceUuid,omitempty"`
	FrontendRedirectUrl *string     `json:"frontendRedirectUrl,omitempty"`
	Provider            string      `json:"provider"`
}

// OidcProviderDto OIDC 提供者（clientSecret 明文可见——admin 可见，参考即如此）。
type OidcProviderDto struct {
	ClientId     string              `json:"clientId"`
	ClientSecret string              `json:"clientSecret"`
	CreatedAt    *time.Time          `json:"createdAt,omitempty"`
	Enabled      bool                `json:"enabled"`
	Guid         string              `json:"guid"`
	Issuer       string              `json:"issuer"`
	Name         string              `json:"name"`
	Priority     int                 `json:"priority"`
	Scope        string              `json:"scope"`
	Type         OidcProviderDtoType `json:"type"`
}

// OidcProviderDtoType defines model for OidcProviderDto.Type.
type OidcProviderDtoType string

// OidcProviderPage 提供者分页（排序 priority ASC + name ASC）。
type OidcProviderPage struct {
	Data  []OidcProviderDto `json:"data"`
	Total int               `json:"total"`
}

// OidcProviderUpsert 创建（POST=200；type 缺省 oidc、scope 按 type 缺省、enabled 缺省 true；重名 400）。
type OidcProviderUpsert struct {
	ClientId     string                  `json:"clientId"`
	ClientSecret string                  `json:"clientSecret"`
	Enabled      *bool                   `json:"enabled,omitempty"`
	Issuer       string                  `json:"issuer"`
	Name         string                  `json:"name"`
	Priority     *int                    `json:"priority,omitempty"`
	Scope        *string                 `json:"scope,omitempty"`
	Type         *OidcProviderUpsertType `json:"type,omitempty"`
}

// OidcProviderUpsertType defines model for OidcProviderUpsert.Type.
type OidcProviderUpsertType string

// PasskeyView defines model for PasskeyView.
type PasskeyView struct {
	BackedUp   *bool      `json:"backedUp,omitempty"`
	CreatedAt  *time.Time `json:"createdAt,omitempty"`
	DeviceType *string    `json:"deviceType,omitempty"`
	Guid       string     `json:"guid"`
	Name       *string    `json:"name,omitempty"`
}

// PeerInfo defines model for PeerInfo.
type PeerInfo struct {
	Cpu string `json:"cpu"`

	// DeviceName sysinfos.hostname
	DeviceName string `json:"device_name"`

	// Ip 恒为空串
	Ip     string `json:"ip"`
	Memory string `json:"memory"`
	Os     string `json:"os"`

	// Username sysinfos.username
	Username string `json:"username"`

	// Version ver 格式化结果（ver=0 → 空串）
	Version string `json:"version"`
}

// PeerPage defines model for PeerPage.
type PeerPage struct {
	Data  []PeerView `json:"data"`
	Total int        `json:"total"`
}

// PeerView defines model for PeerView.
type PeerView struct {
	DeviceGroupName string `json:"device_group_name"`

	// Guid = peer.uuid
	Guid string `json:"guid"`

	// Id peer.id（数字设备 ID 字符串）
	Id   string   `json:"id"`
	Info PeerInfo `json:"info"`

	// IsOnline lastHeartbeat > now-60s（60 秒阈值硬编码）
	IsOnline   bool       `json:"is_online"`
	LastOnline *time.Time `json:"last_online"`
	Note       string     `json:"note"`

	// Status 1=正常 / 0=停用
	Status       int    `json:"status"`
	StrategyName string `json:"strategy_name"`

	// User = userGuid 或空串
	User     string `json:"user"`
	UserName string `json:"user_name"`
}

// PermissionDefinition defines model for PermissionDefinition.
type PermissionDefinition struct {
	Action      string                    `json:"action"`
	Assignable  bool                      `json:"assignable"`
	Code        string                    `json:"code"`
	Description *string                   `json:"description,omitempty"`
	Name        string                    `json:"name"`
	Requires    []string                  `json:"requires"`
	Resource    string                    `json:"resource"`
	Scope       PermissionDefinitionScope `json:"scope"`
	SystemOnly  bool                      `json:"system_only"`
}

// PermissionDefinitionScope defines model for PermissionDefinition.Scope.
type PermissionDefinitionScope string

// ProtectionImpact defines model for ProtectionImpact.
type ProtectionImpact struct {
	AffectedMemberCount int `json:"affected_member_count"`
}

// RemoveDevicesResult defines model for RemoveDevicesResult.
type RemoveDevicesResult struct {
	RemovedCount int `json:"removed_count"`
}

// ReplaceRolesRequest defines model for ReplaceRolesRequest.
type ReplaceRolesRequest struct {
	Assignments []struct {
		DeviceGroupGuids *[]string                               `json:"device_group_guids,omitempty"`
		RoleGuid         string                                  `json:"role_guid"`
		ScopeType        ReplaceRolesRequestAssignmentsScopeType `json:"scope_type"`
	} `json:"assignments"`
}

// ReplaceRolesRequestAssignmentsScopeType defines model for ReplaceRolesRequest.Assignments.ScopeType.
type ReplaceRolesRequestAssignmentsScopeType string

// RoleCreateRequest defines model for RoleCreateRequest.
type RoleCreateRequest struct {
	Name             string    `json:"name"`
	Note             *string   `json:"note,omitempty"`
	Permissions      *[]string `json:"permissions,omitempty"`
	ProtectedAccount *bool     `json:"protected_account,omitempty"`
}

// RoleDetail defines model for RoleDetail.
type RoleDetail struct {
	CreatedAt        time.Time `json:"created_at"`
	Guid             string    `json:"guid"`
	Name             string    `json:"name"`
	Note             string    `json:"note"`
	Permissions      []string  `json:"permissions"`
	ProtectedAccount bool      `json:"protected_account"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// RolePage defines model for RolePage.
type RolePage struct {
	Data  []RoleView `json:"data"`
	Total int        `json:"total"`
}

// RoleUpdateRequest defines model for RoleUpdateRequest.
type RoleUpdateRequest struct {
	// ConfirmProtectedAccountChange 取消保护（true→false）必须为 true
	ConfirmProtectedAccountChange *bool     `json:"confirm_protected_account_change,omitempty"`
	Name                          *string   `json:"name,omitempty"`
	Note                          *string   `json:"note,omitempty"`
	Permissions                   *[]string `json:"permissions,omitempty"`
	ProtectedAccount              *bool     `json:"protected_account,omitempty"`
}

// RoleView defines model for RoleView.
type RoleView struct {
	CreatedAt        time.Time `json:"created_at"`
	Guid             string    `json:"guid"`
	Name             string    `json:"name"`
	Note             string    `json:"note"`
	ProtectedAccount bool      `json:"protected_account"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// RuleGuidsRequest 批量删规则（逐条 FULL_CONTROL 复核）。
type RuleGuidsRequest struct {
	Guids []string `json:"guids"`
}

// ServerBansDto 封禁名单（device_ids ≤10000；ips 标准 IP 格式）。
type ServerBansDto struct {
	DeviceIds []string `json:"device_ids"`
	Ips       []string `json:"ips"`
}

// ServerConfigDto 服务配置透传（键校验归 agent 端；面板只做 JSON object 校验）。
type ServerConfigDto struct {
	Values map[string]string `json:"values"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	CreatedAt  time.Time `json:"createdAt"`
	DeviceId   *string   `json:"deviceId,omitempty"`
	DeviceName *string   `json:"deviceName,omitempty"`
	DeviceOs   *string   `json:"deviceOs,omitempty"`
	DeviceType *string   `json:"deviceType,omitempty"`
	DeviceUuid *string   `json:"deviceUuid,omitempty"`
	ExpiresAt  time.Time `json:"expiresAt"`
	Jti        string    `json:"jti"`
}

// SettingsTestResult 连通性测试恒 200（连接失败也是 success:false）。
type SettingsTestResult struct {
	// Endpoints oidc test discovery 端点
	Endpoints *map[string]interface{} `json:"endpoints,omitempty"`
	Message   string                  `json:"message"`
	Success   bool                    `json:"success"`
}

// ShareCandidates 可分享候选（users + groups 两源）。
type ShareCandidates struct {
	Groups []struct {
		Guid string `json:"guid"`
		Name string `json:"name"`
	} `json:"groups"`
	Users []struct {
		Guid     string  `json:"guid"`
		Name     *string `json:"name,omitempty"`
		Username string  `json:"username"`
	} `json:"users"`
}

// SharedBookList sharedOnly 形态（无 total）。
type SharedBookList struct {
	Data []SharedBookRow `json:"data"`
}

// SharedBookPage custom/shared 书分页（custom 过滤定义 isPersonal=0 AND isShared=0 AND 非外部授权）。
type SharedBookPage struct {
	Data  []SharedBookRow `json:"data"`
	Total int             `json:"total"`
}

// SharedBookRow 书行形态：rule = MAX(owner→FULL_CONTROL, 规则并集最大值)； 排序 name ASC + guid ASC。
type SharedBookRow struct {
	Guid    string  `json:"guid"`
	Info    *string `json:"info,omitempty"`
	IsOwner *bool   `json:"is_owner,omitempty"`
	Name    string  `json:"name"`
	Note    *string `json:"note,omitempty"`

	// Owner owner 用户名
	Owner string `json:"owner"`

	// Rule READ=1 / READ_WRITE=2 / FULL_CONTROL=3
	Rule SharedBookRowRule `json:"rule"`
}

// SharedBookRowRule READ=1 / READ_WRITE=2 / FULL_CONTROL=3
type SharedBookRowRule int

// SmtpConfig SMTP 配置（pass 回读恒 '******'，PUT 命中掩码跳过更新； 无配置时 GET 404 SMTP configuration does not exist）。
type SmtpConfig struct {
	Enabled *bool   `json:"enabled,omitempty"`
	From    *string `json:"from,omitempty"`
	Host    *string `json:"host,omitempty"`
	Pass    *string `json:"pass,omitempty"`
	Port    *int    `json:"port,omitempty"`
	Secure  *bool   `json:"secure,omitempty"`
	User    *string `json:"user,omitempty"`
}

// StrategyCandidatePage defines model for StrategyCandidatePage.
type StrategyCandidatePage struct {
	Data  []StrategyCandidateView `json:"data"`
	Total int                     `json:"total"`
}

// StrategyCandidateView defines model for StrategyCandidateView.
type StrategyCandidateView struct {
	Guid string `json:"guid"`
	Name string `json:"name"`
	Note string `json:"note"`
}

// StrategyPage defines model for StrategyPage.
type StrategyPage struct {
	Data  []StrategyView `json:"data"`
	Total int            `json:"total"`
}

// StrategyUpsertRequest defines model for StrategyUpsertRequest.
type StrategyUpsertRequest struct {
	ConfigOptions *map[string]string `json:"config_options,omitempty"`
	Name          string             `json:"name"`
	Note          *string            `json:"note,omitempty"`
}

// StrategyView defines model for StrategyView.
type StrategyView struct {
	// ConfigOptions DB TEXT 存 JSON 串，读出解析；空串 → {}
	ConfigOptions map[string]string `json:"config_options"`
	CreatedAt     time.Time         `json:"created_at"`
	Guid          string            `json:"guid"`
	Name          string            `json:"name"`
	Note          string            `json:"note"`
	UpdatedAt     time.Time         `json:"updated_at"`
}

// SysinfoRequest defines model for SysinfoRequest.
type SysinfoRequest struct {
	Cpu                    *string `json:"cpu,omitempty"`
	Hostname               *string `json:"hostname,omitempty"`
	Id                     *string `json:"id,omitempty"`
	Memory                 *string `json:"memory,omitempty"`
	Os                     *string `json:"os,omitempty"`
	PresetAddressBookAlias *string `json:"preset-address-book-alias,omitempty"`

	// PresetAddressBookName M2 接受不处理（M3 通讯录联动）
	PresetAddressBookName     *string `json:"preset-address-book-name,omitempty"`
	PresetAddressBookNote     *string `json:"preset-address-book-note,omitempty"`
	PresetAddressBookPassword *string `json:"preset-address-book-password,omitempty"`
	PresetAddressBookTag      *string `json:"preset-address-book-tag,omitempty"`

	// PresetDeviceGroupName 按名关联 device_groups 并回写 peers.deviceGroupGuid
	PresetDeviceGroupName *string `json:"preset-device-group-name,omitempty"`

	// PresetNote 仅当 peers.note 为空时写入
	PresetNote         *string `json:"preset-note,omitempty"`
	PresetStrategyName *string `json:"preset-strategy-name,omitempty"`

	// PresetUsername 非空真值才覆盖 sysinfos.preset_username
	PresetUsername *string `json:"preset-username,omitempty"`
	Username       *string `json:"username,omitempty"`
	Uuid           string  `json:"uuid"`
	Version        *string `json:"version,omitempty"`
}

// UpdateBookProfileRequest custom 书 profile 更新（owner 复核；至少一键否则 400）。
type UpdateBookProfileRequest struct {
	Info *struct {
		Password *string `json:"password,omitempty"`
	} `json:"info,omitempty"`
	Name     *string `json:"name,omitempty"`
	Note     *string `json:"note,omitempty"`
	Password *string `json:"password,omitempty"`
}

// UpdateCheckResult 更新检查（内存缓存 + frontend_version 仅影响 frontend 分支比对）。
type UpdateCheckResult struct {
	Backend struct {
		Current     string  `json:"current"`
		DownloadUrl *string `json:"downloadUrl,omitempty"`
		HasUpdate   bool    `json:"hasUpdate"`
		Latest      string  `json:"latest"`
	} `json:"backend"`
	Frontend struct {
		Current     string  `json:"current"`
		DownloadUrl *string `json:"downloadUrl,omitempty"`
		HasUpdate   bool    `json:"hasUpdate"`
		Latest      string  `json:"latest"`
	} `json:"frontend"`
	InstallId *string `json:"install_id,omitempty"`
}

// UpdateDeviceRequest defines model for UpdateDeviceRequest.
type UpdateDeviceRequest struct {
	// DeviceGroupName 关联变更需 super administrator；空串解绑
	DeviceGroupName *string `json:"deviceGroupName"`
	Note            *string `json:"note,omitempty"`

	// StrategyName 关联变更需 super administrator；空串解绑
	StrategyName *string `json:"strategyName"`

	// UserName 关联变更需 super administrator；空串解绑
	UserName *string `json:"userName"`
}

// UpdateGeneralSettings 更新通用设置（watermarkEnabled 必填；defaultLanguage 匹配 ^[a-z]{2}-[A-Z]{2}$； jwtExpiryDays≥1；auditRetentionDays≥0）。
type UpdateGeneralSettings struct {
	AuditRetentionDays *int    `json:"auditRetentionDays,omitempty"`
	DefaultLanguage    *string `json:"defaultLanguage,omitempty"`
	JwtExpiryDays      *int    `json:"jwtExpiryDays,omitempty"`
	SiteBackendUrl     *string `json:"siteBackendUrl,omitempty"`
	SiteFrontendUrl    *string `json:"siteFrontendUrl,omitempty"`
	WatermarkEnabled   bool    `json:"watermarkEnabled"`
	WebauthnEnabled    *bool   `json:"webauthnEnabled,omitempty"`
	WebauthnRpName     *string `json:"webauthnRpName,omitempty"`
}

// UpdateMeRequest user 域请求字段为 snake_case（契约，禁止规范化）。
type UpdateMeRequest struct {
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Note        *string              `json:"note,omitempty"`
}

// UpdateSharedBookRequest 共享书更新：改 owner 需 FULL_CONTROL（先给新 owner 授 FULL_CONTROL 规则）； 改 name/note/password 需 READ_WRITE；重名 409。
type UpdateSharedBookRequest struct {
	Guid string  `json:"guid"`
	Name *string `json:"name,omitempty"`
	Note *string `json:"note,omitempty"`

	// Owner 新 owner 用户名（不存在 404 New owner user does not exist）
	Owner    *string `json:"owner,omitempty"`
	Password *string `json:"password,omitempty"`
}

// UpdateUserRequest 按字段分权（name/display_name/email/note→users.edit；status→users.status； user_group_guid→user_groups.membership）；is_admin 一律 400；全空 body 400。
type UpdateUserRequest struct {
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Name        *string              `json:"name,omitempty"`
	Note        *string              `json:"note,omitempty"`

	// Status 变更时同一事务内 revokeActiveTokens
	Status        *UpdateUserRequestStatus `json:"status,omitempty"`
	UserGroupGuid *string                  `json:"user_group_guid,omitempty"`
}

// UpdateUserRequestStatus 变更时同一事务内 revokeActiveTokens
type UpdateUserRequestStatus int

// UpdateUserSecurityRequest 安全设置（tfa_enforce/email_verification 写 users.info JSON）。
type UpdateUserSecurityRequest struct {
	EmailVerification *bool   `json:"email_verification,omitempty"`
	NewPassword       *string `json:"new_password,omitempty"`
	TfaEnforce        *bool   `json:"tfa_enforce,omitempty"`
}

// UserGroupPage defines model for UserGroupPage.
type UserGroupPage struct {
	Data  []UserGroupView `json:"data"`
	Total int             `json:"total"`
}

// UserGroupUpsertRequest defines model for UserGroupUpsertRequest.
type UserGroupUpsertRequest struct {
	Name string  `json:"name"`
	Note *string `json:"note,omitempty"`
}

// UserGroupView defines model for UserGroupView.
type UserGroupView struct {
	Guid      string `json:"guid"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
	Note      string `json:"note"`
	UserCount int    `json:"user_count"`
}

// UserPage defines model for UserPage.
type UserPage struct {
	Data  []UserView `json:"data"`
	Total int        `json:"total"`
}

// UserPayload 用户响应 payload（snake_case 契约，禁止规范化）。
type UserPayload struct {
	Avatar        *string `json:"avatar,omitempty"`
	DisplayName   *string `json:"display_name,omitempty"`
	Email         *string `json:"email,omitempty"`
	Guid          string  `json:"guid"`
	HasPassword   *bool   `json:"has_password,omitempty"`
	IsAdmin       bool    `json:"is_admin"`
	Name          string  `json:"name"`
	Note          *string `json:"note,omitempty"`
	StrategyGuid  *string `json:"strategy_guid,omitempty"`
	TfaEnabled    *bool   `json:"tfa_enabled,omitempty"`
	ThirdAuthType *string `json:"third_auth_type,omitempty"`
	UserGroupGuid *string `json:"user_group_guid,omitempty"`
	Verifier      *string `json:"verifier,omitempty"`
}

// UserRolesResult defines model for UserRolesResult.
type UserRolesResult struct {
	Data []AssignmentDto `json:"data"`

	// EffectiveScope 用户全部 assignment 聚合 scope
	EffectiveScope UserRolesResultEffectiveScope `json:"effective_scope"`
}

// UserRolesResultEffectiveScope 用户全部 assignment 聚合 scope
type UserRolesResultEffectiveScope string

// UserTargetPage defines model for UserTargetPage.
type UserTargetPage struct {
	Data  []UserTargetView `json:"data"`
	Total int              `json:"total"`
}

// UserTargetView defines model for UserTargetView.
type UserTargetView struct {
	Guid        string `json:"guid"`
	IsProtected bool   `json:"is_protected"`

	// Name displayName || username
	Name string `json:"name"`
}

// UserView 用户视图（is_protected 保护账号标记）。
type UserView struct {
	DisplayName *string `json:"display_name,omitempty"`
	Email       *string `json:"email,omitempty"`
	Guid        string  `json:"guid"`
	IsProtected bool    `json:"is_protected"`
	Name        string  `json:"name"`
	Note        *string `json:"note,omitempty"`

	// Status UNVERIFIED=-1 / DISABLED=0 / ACTIVE=1
	Status        int     `json:"status"`
	UserGroupGuid *string `json:"user_group_guid,omitempty"`
	Username      string  `json:"username"`
}

// CurrentParam defines model for CurrentParam.
type CurrentParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// BadRequest NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type BadRequest = Error

// Conflict NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type Conflict = Error

// Forbidden NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type Forbidden = Error

// NotFound NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type NotFound = Error

// Unauthorized NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type Unauthorized = Error

// DisableTfaJSONBody defines parameters for DisableTfa.
type DisableTfaJSONBody struct {
	TfaCode string `json:"tfaCode"`
}

// VerifyTfaJSONBody defines parameters for VerifyTfa.
type VerifyTfaJSONBody struct {
	TfaCode string `json:"tfaCode"`
}

// ListCustomAddressBooksParams defines parameters for ListCustomAddressBooks.
type ListCustomAddressBooksParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Name     *string        `form:"name,omitempty" json:"name,omitempty"`
	Note     *string        `form:"note,omitempty" json:"note,omitempty"`
}

// ListAddressBookPeersParams defines parameters for ListAddressBookPeers.
type ListAddressBookPeersParams struct {
	// Ab 地址簿 guid
	Ab    string  `form:"ab" json:"ab"`
	Id    *string `form:"id,omitempty" json:"id,omitempty"`
	Alias *string `form:"alias,omitempty" json:"alias,omitempty"`

	// Tags 逗号分隔 tag guid 列表
	Tags    *string                            `form:"tags,omitempty" json:"tags,omitempty"`
	TagMode *ListAddressBookPeersParamsTagMode `form:"tagMode,omitempty" json:"tagMode,omitempty"`
}

// ListAddressBookPeersParamsTagMode defines parameters for ListAddressBookPeers.
type ListAddressBookPeersParamsTagMode string

// ListAddressBookRulesParams defines parameters for ListAddressBookRules.
type ListAddressBookRulesParams struct {
	// Ab 地址簿 guid（缺省=我的全部书）
	Ab *string `form:"ab,omitempty" json:"ab,omitempty"`
}

// ListSharedAddressBookProfilesParams defines parameters for ListSharedAddressBookProfiles.
type ListSharedAddressBookProfilesParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Name     *string        `form:"name,omitempty" json:"name,omitempty"`
	Note     *string        `form:"note,omitempty" json:"note,omitempty"`
}

// ListShareCandidatesParams defines parameters for ListShareCandidates.
type ListShareCandidatesParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListAdminUsersParams defines parameters for ListAdminUsers.
type ListAdminUsersParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Status   *string        `form:"status,omitempty" json:"status,omitempty"`

	// Name LIKE 匹配
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Email LIKE 匹配
	Email         *string                      `form:"email,omitempty" json:"email,omitempty"`
	IsAdmin       *ListAdminUsersParamsIsAdmin `form:"is_admin,omitempty" json:"is_admin,omitempty"`
	ThirdAuthType *string                      `form:"third_auth_type,omitempty" json:"third_auth_type,omitempty"`
	StrategyName  *string                      `form:"strategy_name,omitempty" json:"strategy_name,omitempty"`
	UserGroupGuid *string                      `form:"user_group_guid,omitempty" json:"user_group_guid,omitempty"`
	UserGroupName *string                      `form:"user_group_name,omitempty" json:"user_group_name,omitempty"`
}

// ListAdminUsersParamsIsAdmin defines parameters for ListAdminUsers.
type ListAdminUsersParamsIsAdmin string

// ListAlarmAuditsParams defines parameters for ListAlarmAudits.
type ListAlarmAuditsParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Typ      *int           `form:"typ,omitempty" json:"typ,omitempty"`
	Uuid     *string        `form:"uuid,omitempty" json:"uuid,omitempty"`
}

// ListConnectionAuditsParams defines parameters for ListConnectionAudits.
type ListConnectionAuditsParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PeerId   *string        `form:"peer_id,omitempty" json:"peer_id,omitempty"`
	Uuid     *string        `form:"uuid,omitempty" json:"uuid,omitempty"`
	Type     *int           `form:"type,omitempty" json:"type,omitempty"`
	Start    *time.Time     `form:"start,omitempty" json:"start,omitempty"`
	End      *time.Time     `form:"end,omitempty" json:"end,omitempty"`
}

// ListConsoleAuditsParams defines parameters for ListConsoleAudits.
type ListConsoleAuditsParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam                 `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	Result   *ListConsoleAuditsParamsResult `form:"result,omitempty" json:"result,omitempty"`
	UserGuid *string                        `form:"user_guid,omitempty" json:"user_guid,omitempty"`
}

// ListConsoleAuditsParamsResult defines parameters for ListConsoleAudits.
type ListConsoleAuditsParamsResult string

// ListFileAuditsParams defines parameters for ListFileAudits.
type ListFileAuditsParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PeerId   *string        `form:"peer_id,omitempty" json:"peer_id,omitempty"`
	Uuid     *string        `form:"uuid,omitempty" json:"uuid,omitempty"`
	Type     *int           `form:"type,omitempty" json:"type,omitempty"`
}

// GetDashboardTrendsParams defines parameters for GetDashboardTrends.
type GetDashboardTrendsParams struct {
	Range *GetDashboardTrendsParamsRange `form:"range,omitempty" json:"range,omitempty"`
}

// GetDashboardTrendsParamsRange defines parameters for GetDashboardTrends.
type GetDashboardTrendsParamsRange string

// AccessibleDeviceGroupsParams defines parameters for AccessibleDeviceGroups.
type AccessibleDeviceGroupsParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListDeviceGroupsParams defines parameters for ListDeviceGroups.
type ListDeviceGroupsParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// DeviceGroupStrategyTargetsParams defines parameters for DeviceGroupStrategyTargets.
type DeviceGroupStrategyTargetsParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// AddDeviceGroupDevicesJSONBody defines parameters for AddDeviceGroupDevices.
type AddDeviceGroupDevicesJSONBody = []string

// RemoveDeviceGroupDevicesJSONBody defines parameters for RemoveDeviceGroupDevices.
type RemoveDeviceGroupDevicesJSONBody = []string

// ListDevicesParams defines parameters for ListDevices.
type ListDevicesParams struct {
	Id       *string                    `form:"id,omitempty" json:"id,omitempty"`
	Status   *ListDevicesParamsStatus   `form:"status,omitempty" json:"status,omitempty"`
	IsOnline *ListDevicesParamsIsOnline `form:"is_online,omitempty" json:"is_online,omitempty"`

	// DeviceName LIKE 匹配 sysinfos.hostname
	DeviceName *string `form:"device_name,omitempty" json:"device_name,omitempty"`
	UserName   *string `form:"user_name,omitempty" json:"user_name,omitempty"`

	// DeviceUsername LIKE 匹配 sysinfos.username
	DeviceUsername *string `form:"device_username,omitempty" json:"device_username,omitempty"`
	Os             *string `form:"os,omitempty" json:"os,omitempty"`

	// DeviceGroupName 精确匹配（与 /peers 的 LIKE 不同）
	DeviceGroupName *string `form:"device_group_name,omitempty" json:"device_group_name,omitempty"`
	DeviceGroupGuid *string `form:"device_group_guid,omitempty" json:"device_group_guid,omitempty"`

	// GroupName LIKE 匹配设备组名
	GroupName *string `form:"group_name,omitempty" json:"group_name,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListDevicesParamsStatus defines parameters for ListDevices.
type ListDevicesParamsStatus string

// ListDevicesParamsIsOnline defines parameters for ListDevices.
type ListDevicesParamsIsOnline string

// GetNexusLoginStatusParams defines parameters for GetNexusLoginStatus.
type GetNexusLoginStatusParams struct {
	LoginId string `form:"login_id" json:"login_id"`
}

// ListOidcProvidersParams defines parameters for ListOidcProviders.
type ListOidcProvidersParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SortOidcProvidersJSONBody defines parameters for SortOidcProviders.
type SortOidcProvidersJSONBody = []string

// OidcAuthQueryParams defines parameters for OidcAuthQuery.
type OidcAuthQueryParams struct {
	Code string  `form:"code" json:"code"`
	Id   *string `form:"id,omitempty" json:"id,omitempty"`
	Uuid *string `form:"uuid,omitempty" json:"uuid,omitempty"`
}

// OidcCallbackParams defines parameters for OidcCallback.
type OidcCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// PasskeyAuthVerifyJSONBody defines parameters for PasskeyAuthVerify.
type PasskeyAuthVerifyJSONBody struct {
	DeviceInfo *DeviceInfo            `json:"deviceInfo,omitempty"`
	Id         *string                `json:"id,omitempty"`
	Response   map[string]interface{} `json:"response"`
	Secret     string                 `json:"secret"`
	Uuid       *string                `json:"uuid,omitempty"`
}

// PasskeyRegisterVerifyJSONBody defines parameters for PasskeyRegisterVerify.
type PasskeyRegisterVerifyJSONBody struct {
	Name     *string                `json:"name,omitempty"`
	Response map[string]interface{} `json:"response"`
}

// PasskeyTfaToggleJSONBody defines parameters for PasskeyTfaToggle.
type PasskeyTfaToggleJSONBody struct {
	Enabled bool `json:"enabled"`
}

// ListPeersParams defines parameters for ListPeers.
type ListPeersParams struct {
	// Accessible 兼容字段，忽略
	Accessible      *string                  `form:"accessible,omitempty" json:"accessible,omitempty"`
	Id              *string                  `form:"id,omitempty" json:"id,omitempty"`
	Status          *ListPeersParamsStatus   `form:"status,omitempty" json:"status,omitempty"`
	IsOnline        *ListPeersParamsIsOnline `form:"is_online,omitempty" json:"is_online,omitempty"`
	UserName        *string                  `form:"user_name,omitempty" json:"user_name,omitempty"`
	DeviceGroupGuid *string                  `form:"device_group_guid,omitempty" json:"device_group_guid,omitempty"`

	// DeviceGroupName LIKE 匹配（与 /devices 的精确匹配不同）
	DeviceGroupName *string `form:"device_group_name,omitempty" json:"device_group_name,omitempty"`

	// Os LIKE 匹配 sysinfos.os
	Os *string `form:"os,omitempty" json:"os,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListPeersParamsStatus defines parameters for ListPeers.
type ListPeersParamsStatus string

// ListPeersParamsIsOnline defines parameters for ListPeers.
type ListPeersParamsIsOnline string

// ListRolesParams defines parameters for ListRoles.
type ListRolesParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
	Note *string `form:"note,omitempty" json:"note,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetServerServiceConfigParamsService defines parameters for GetServerServiceConfig.
type GetServerServiceConfigParamsService string

// UpdateServerServiceConfigParamsService defines parameters for UpdateServerServiceConfig.
type UpdateServerServiceConfigParamsService string

// GetServerServiceLogsParamsService defines parameters for GetServerServiceLogs.
type GetServerServiceLogsParamsService string

// RunServerServiceActionParamsService defines parameters for RunServerServiceAction.
type RunServerServiceActionParamsService string

// RunServerServiceActionParamsAction defines parameters for RunServerServiceAction.
type RunServerServiceActionParamsAction string

// ListStrategiesParams defines parameters for ListStrategies.
type ListStrategiesParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// StrategyCandidatesParams defines parameters for StrategyCandidates.
type StrategyCandidatesParams struct {
	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// StrategyTargetCandidatesParams defines parameters for StrategyTargetCandidates.
type StrategyTargetCandidatesParams struct {
	TargetType StrategyTargetCandidatesParamsTargetType `form:"target_type" json:"target_type"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// StrategyTargetCandidatesParamsTargetType defines parameters for StrategyTargetCandidates.
type StrategyTargetCandidatesParamsTargetType string

// StrategyAssignmentsParams defines parameters for StrategyAssignments.
type StrategyAssignmentsParams struct {
	TargetType StrategyAssignmentsParamsTargetType `form:"target_type" json:"target_type"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// StrategyAssignmentsParamsTargetType defines parameters for StrategyAssignments.
type StrategyAssignmentsParamsTargetType string

// GetUpdateCheckParams defines parameters for GetUpdateCheck.
type GetUpdateCheckParams struct {
	FrontendVersion *string `form:"frontend_version,omitempty" json:"frontend_version,omitempty"`
}

// ListUserGroupsParams defines parameters for ListUserGroups.
type ListUserGroupsParams struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListUserGroupMembersParams defines parameters for ListUserGroupMembers.
type ListUserGroupMembersParams struct {
	// Search LIKE 匹配 username 或 email
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Current 页码（1~100000，默认 1；camelCase 契约，禁止规范化）
	Current *CurrentParam `form:"current,omitempty" json:"current,omitempty"`

	// PageSize 每页条数（1~100，默认 20；camelCase 契约，禁止规范化）
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Status admin 分支过滤（'1' 活跃 / '0' 停用 / '-1' 未验证；缺省 '1'；非 admin 忽略）
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// UploadMyAvatarMultipartBody defines parameters for UploadMyAvatar.
type UploadMyAvatarMultipartBody struct {
	Avatar openapi_types.File `json:"avatar"`
}

// DisableTfaJSONRequestBody defines body for DisableTfa for application/json ContentType.
type DisableTfaJSONRequestBody DisableTfaJSONBody

// VerifyTfaJSONRequestBody defines body for VerifyTfa for application/json ContentType.
type VerifyTfaJSONRequestBody VerifyTfaJSONBody

// UpdateLegacyAddressBookJSONRequestBody defines body for UpdateLegacyAddressBook for application/json ContentType.
type UpdateLegacyAddressBookJSONRequestBody = LegacyAbSaveRequest

// DeleteCustomAddressBooksJSONRequestBody defines body for DeleteCustomAddressBooks for application/json ContentType.
type DeleteCustomAddressBooksJSONRequestBody = BookGuidsRequest

// CreateCustomAddressBookJSONRequestBody defines body for CreateCustomAddressBook for application/json ContentType.
type CreateCustomAddressBookJSONRequestBody = CreateBookProfileRequest

// UpdateCustomAddressBookProfileJSONRequestBody defines body for UpdateCustomAddressBookProfile for application/json ContentType.
type UpdateCustomAddressBookProfileJSONRequestBody = UpdateBookProfileRequest

// AddAddressBookPeerJSONRequestBody defines body for AddAddressBookPeer for application/json ContentType.
type AddAddressBookPeerJSONRequestBody = AbPeerUpsertRequest

// UpdateAddressBookPeerJSONRequestBody defines body for UpdateAddressBookPeer for application/json ContentType.
type UpdateAddressBookPeerJSONRequestBody = AbPeerUpsertRequest

// QueryAddressBookPeersJSONRequestBody defines body for QueryAddressBookPeers for application/json ContentType.
type QueryAddressBookPeersJSONRequestBody = AbPeersQueryRequest

// UpdateAddressBookRuleJSONRequestBody defines body for UpdateAddressBookRule for application/json ContentType.
type UpdateAddressBookRuleJSONRequestBody = AbRuleUpdateRequest

// CreateAddressBookRuleJSONRequestBody defines body for CreateAddressBookRule for application/json ContentType.
type CreateAddressBookRuleJSONRequestBody = AbRuleUpsertRequest

// DeleteAddressBookRulesJSONRequestBody defines body for DeleteAddressBookRules for application/json ContentType.
type DeleteAddressBookRulesJSONRequestBody = RuleGuidsRequest

// DeleteSharedAddressBooksJSONRequestBody defines body for DeleteSharedAddressBooks for application/json ContentType.
type DeleteSharedAddressBooksJSONRequestBody = BookGuidsRequest

// CreateSharedAddressBookJSONRequestBody defines body for CreateSharedAddressBook for application/json ContentType.
type CreateSharedAddressBookJSONRequestBody = CreateBookProfileRequest

// QuerySharedAddressBookProfilesJSONRequestBody defines body for QuerySharedAddressBookProfiles for application/json ContentType.
type QuerySharedAddressBookProfilesJSONRequestBody = BookPaginationRequest

// UpdateSharedAddressBookJSONRequestBody defines body for UpdateSharedAddressBook for application/json ContentType.
type UpdateSharedAddressBookJSONRequestBody = UpdateSharedBookRequest

// AddAddressBookTagJSONRequestBody defines body for AddAddressBookTag for application/json ContentType.
type AddAddressBookTagJSONRequestBody = AbTagUpsertRequest

// RenameAddressBookTagJSONRequestBody defines body for RenameAddressBookTag for application/json ContentType.
type RenameAddressBookTagJSONRequestBody = AbTagRenameRequest

// UpdateAddressBookTagJSONRequestBody defines body for UpdateAddressBookTag for application/json ContentType.
type UpdateAddressBookTagJSONRequestBody = AbTagUpsertRequest

// ReplaceAddressBookTagsJSONRequestBody defines body for ReplaceAddressBookTags for application/json ContentType.
type ReplaceAddressBookTagsJSONRequestBody = AbTagsReplaceRequest

// ReportAlarmAuditJSONRequestBody defines body for ReportAlarmAudit for application/json ContentType.
type ReportAlarmAuditJSONRequestBody = AlarmAuditReport

// ReportConnAuditJSONRequestBody defines body for ReportConnAudit for application/json ContentType.
type ReportConnAuditJSONRequestBody = ConnAuditReport

// ReportFileAuditJSONRequestBody defines body for ReportFileAudit for application/json ContentType.
type ReportFileAuditJSONRequestBody = FileAuditReport

// UpdateConnectionAuditNoteJSONRequestBody defines body for UpdateConnectionAuditNote for application/json ContentType.
type UpdateConnectionAuditNoteJSONRequestBody = ConnNoteUpdate

// CreateDeviceGroupJSONRequestBody defines body for CreateDeviceGroup for application/json ContentType.
type CreateDeviceGroupJSONRequestBody = DeviceGroupUpsertRequest

// UpdateDeviceGroupJSONRequestBody defines body for UpdateDeviceGroup for application/json ContentType.
type UpdateDeviceGroupJSONRequestBody = DeviceGroupUpsertRequest

// AddDeviceGroupDevicesJSONRequestBody defines body for AddDeviceGroupDevices for application/json ContentType.
type AddDeviceGroupDevicesJSONRequestBody = AddDeviceGroupDevicesJSONBody

// RemoveDeviceGroupDevicesJSONRequestBody defines body for RemoveDeviceGroupDevices for application/json ContentType.
type RemoveDeviceGroupDevicesJSONRequestBody = RemoveDeviceGroupDevicesJSONBody

// UpdateDeviceStatusJSONRequestBody defines body for UpdateDeviceStatus for application/json ContentType.
type UpdateDeviceStatusJSONRequestBody = DeviceStatusUpdateRequest

// UpdateDeviceJSONRequestBody defines body for UpdateDevice for application/json ContentType.
type UpdateDeviceJSONRequestBody = UpdateDeviceRequest

// DisconnectDeviceJSONRequestBody defines body for DisconnectDevice for application/json ContentType.
type DisconnectDeviceJSONRequestBody = DisconnectRequest

// HeartbeatJSONRequestBody defines body for Heartbeat for application/json ContentType.
type HeartbeatJSONRequestBody = HeartbeatRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationAcceptRequest

// VerifyInvitationJSONRequestBody defines body for VerifyInvitation for application/json ContentType.
type VerifyInvitationJSONRequestBody = InvitationTokenRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// CreateNexusBuildJSONRequestBody defines body for CreateNexusBuild for application/json ContentType.
type CreateNexusBuildJSONRequestBody = NexusGenerateDto

// CreateOidcProviderJSONRequestBody defines body for CreateOidcProvider for application/json ContentType.
type CreateOidcProviderJSONRequestBody = OidcProviderUpsert

// SortOidcProvidersJSONRequestBody defines body for SortOidcProviders for application/json ContentType.
type SortOidcProvidersJSONRequestBody = SortOidcProvidersJSONBody

// UpdateOidcProviderJSONRequestBody defines body for UpdateOidcProvider for application/json ContentType.
type UpdateOidcProviderJSONRequestBody = OidcProviderUpsert

// OidcAuthJSONRequestBody defines body for OidcAuth for application/json ContentType.
type OidcAuthJSONRequestBody = OidcAuthRequest

// PasskeyAuthVerifyJSONRequestBody defines body for PasskeyAuthVerify for application/json ContentType.
type PasskeyAuthVerifyJSONRequestBody PasskeyAuthVerifyJSONBody

// PasskeyRegisterVerifyJSONRequestBody defines body for PasskeyRegisterVerify for application/json ContentType.
type PasskeyRegisterVerifyJSONRequestBody PasskeyRegisterVerifyJSONBody

// PasskeyTfaToggleJSONRequestBody defines body for PasskeyTfaToggle for application/json ContentType.
type PasskeyTfaToggleJSONRequestBody PasskeyTfaToggleJSONBody

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = RoleCreateRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = RoleUpdateRequest

// UpdateServerBansJSONRequestBody defines body for UpdateServerBans for application/json ContentType.
type UpdateServerBansJSONRequestBody = ServerBansDto

// UpdateServerServiceConfigJSONRequestBody defines body for UpdateServerServiceConfig for application/json ContentType.
type UpdateServerServiceConfigJSONRequestBody = ServerConfigDto

// UpdateGeneralSettingsJSONRequestBody defines body for UpdateGeneralSettings for application/json ContentType.
type UpdateGeneralSettingsJSONRequestBody = UpdateGeneralSettings

// UpdateLdapSettingsJSONRequestBody defines body for UpdateLdapSettings for application/json ContentType.
type UpdateLdapSettingsJSONRequestBody = LdapConfig

// TestLdapSettingsJSONRequestBody defines body for TestLdapSettings for application/json ContentType.
type TestLdapSettingsJSONRequestBody = LdapConfig

// UpdateSmtpSettingsJSONRequestBody defines body for UpdateSmtpSettings for application/json ContentType.
type UpdateSmtpSettingsJSONRequestBody = SmtpConfig

// TestSmtpSettingsJSONRequestBody defines body for TestSmtpSettings for application/json ContentType.
type TestSmtpSettingsJSONRequestBody = SmtpConfig

// CreateStrategyJSONRequestBody defines body for CreateStrategy for application/json ContentType.
type CreateStrategyJSONRequestBody = StrategyUpsertRequest

// UpdateStrategyJSONRequestBody defines body for UpdateStrategy for application/json ContentType.
type UpdateStrategyJSONRequestBody = StrategyUpsertRequest

// AssignStrategyJSONRequestBody defines body for AssignStrategy for application/json ContentType.
type AssignStrategyJSONRequestBody = AssignRequest

// UnassignStrategyJSONRequestBody defines body for UnassignStrategy for application/json ContentType.
type UnassignStrategyJSONRequestBody = AssignRequest

// SysinfoJSONRequestBody defines body for Sysinfo for application/json ContentType.
type SysinfoJSONRequestBody = SysinfoRequest

// CreateUserGroupJSONRequestBody defines body for CreateUserGroup for application/json ContentType.
type CreateUserGroupJSONRequestBody = UserGroupUpsertRequest

// UpdateUserGroupJSONRequestBody defines body for UpdateUserGroup for application/json ContentType.
type UpdateUserGroupJSONRequestBody = UserGroupUpsertRequest

// AddUserGroupMembersJSONRequestBody defines body for AddUserGroupMembers for application/json ContentType.
type AddUserGroupMembersJSONRequestBody = MoveUsersRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// BatchUpdateUserSecurityJSONRequestBody defines body for BatchUpdateUserSecurity for application/json ContentType.
type BatchUpdateUserSecurityJSONRequestBody = BatchSecurityRequest

// BatchForceUserLogoutJSONRequestBody defines body for BatchForceUserLogout for application/json ContentType.
type BatchForceUserLogoutJSONRequestBody = BatchSessionsRequest

// BatchUpdateUserStatusJSONRequestBody defines body for BatchUpdateUserStatus for application/json ContentType.
type BatchUpdateUserStatusJSONRequestBody = BatchStatusRequest

// InviteUserJSONRequestBody defines body for InviteUser for application/json ContentType.
type InviteUserJSONRequestBody = InviteUserRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// UploadMyAvatarMultipartRequestBody defines body for UploadMyAvatar for multipart/form-data ContentType.
type UploadMyAvatarMultipartRequestBody UploadMyAvatarMultipartBody

// ChangeMyPasswordJSONRequestBody defines body for ChangeMyPassword for application/json ContentType.
type ChangeMyPasswordJSONRequestBody = ChangePasswordRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// ReplaceUserRolesJSONRequestBody defines body for ReplaceUserRoles for application/json ContentType.
type ReplaceUserRolesJSONRequestBody = ReplaceRolesRequest

// UpdateUserSecurityJSONRequestBody defines body for UpdateUserSecurity for application/json ContentType.
type UpdateUserSecurityJSONRequestBody = UpdateUserSecurityRequest

// AsErrorMessage0 returns the union data inside the Error_Message as a ErrorMessage0
func (t Error_Message) AsErrorMessage0() (ErrorMessage0, error) {
	var body ErrorMessage0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage0 overwrites any union data inside the Error_Message as the provided ErrorMessage0
func (t *Error_Message) FromErrorMessage0(v ErrorMessage0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMessage0 performs a merge with any union data inside the Error_Message, using the provided ErrorMessage0
func (t *Error_Message) MergeErrorMessage0(v ErrorMessage0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMessage1 returns the union data inside the Error_Message as a ErrorMessage1
func (t Error_Message) AsErrorMessage1() (ErrorMessage1, error) {
	var body ErrorMessage1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage1 overwrites any union data inside the Error_Message as the provided ErrorMessage1
func (t *Error_Message) FromErrorMessage1(v ErrorMessage1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMessage1 performs a merge with any union data inside the Error_Message, using the provided ErrorMessage1
func (t *Error_Message) MergeErrorMessage1(v ErrorMessage1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMessage2 returns the union data inside the Error_Message as a ErrorMessage2
func (t Error_Message) AsErrorMessage2() (ErrorMessage2, error) {
	var body ErrorMessage2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage2 overwrites any union data inside the Error_Message as the provided ErrorMessage2
func (t *Error_Message) FromErrorMessage2(v ErrorMessage2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMessage2 performs a merge with any union data inside the Error_Message, using the provided ErrorMessage2
func (t *Error_Message) MergeErrorMessage2(v ErrorMessage2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Error_Message) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Error_Message) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
