// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for LoginRequestType.
const (
	LoginRequestTypeAccount   LoginRequestType = "account"
	LoginRequestTypeEmailCode LoginRequestType = "email_code"
	LoginRequestTypeSmsCode   LoginRequestType = "sms_code"
	LoginRequestTypeTfaCode   LoginRequestType = "tfa_code"
)

// Defines values for LoginResponseTfaType.
const (
	PasskeyCheck LoginResponseTfaType = "passkey_check"
	TfaCheck     LoginResponseTfaType = "tfa_check"
)

// Defines values for LoginResponseType.
const (
	LoginResponseTypeAccount    LoginResponseType = "account"
	LoginResponseTypeEmailCheck LoginResponseType = "email_check"
)

// AvatarResponse defines model for AvatarResponse.
type AvatarResponse struct {
	Avatar string `json:"avatar"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Name *string `json:"name,omitempty"`
	Os   *string `json:"os,omitempty"`
	Type *string `json:"type,omitempty"`
}

// Error NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type Error struct {
	Error      string        `json:"error"`
	Message    Error_Message `json:"message"`
	StatusCode int           `json:"statusCode"`
}

// ErrorMessage0 defines model for .
type ErrorMessage0 = string

// ErrorMessage1 defines model for .
type ErrorMessage1 = []string

// ErrorMessage2 defines model for .
type ErrorMessage2 = map[string]interface{}

// Error_Message defines model for Error.Message.
type Error_Message struct {
	union json.RawMessage
}

// LoginRequest type 分支请求；account 需 username/password， tfa_code 需 secret+tfaCode，email_code 需 secret+verificationCode。
type LoginRequest struct {
	AutoLogin  *bool       `json:"autoLogin,omitempty"`
	DeviceInfo *DeviceInfo `json:"deviceInfo,omitempty"`

	// Id 设备 ID
	Id       *string           `json:"id,omitempty"`
	Password *string           `json:"password,omitempty"`
	Secret   *string           `json:"secret,omitempty"`
	TfaCode  *string           `json:"tfaCode,omitempty"`
	Type     *LoginRequestType `json:"type,omitempty"`
	Username *string           `json:"username,omitempty"`

	// Uuid 设备 UUID
	Uuid             *string `json:"uuid,omitempty"`
	VerificationCode *string `json:"verificationCode,omitempty"`
}

// LoginRequestType defines model for LoginRequest.Type.
type LoginRequestType string

// LoginResponse 分支结构：account 带 access_token+user； 两步验证带 type=email_check + tfa_type + secret； passkey_tfa 第一步复用 email_check 类型位并附 passkey_options。
type LoginResponse struct {
	AccessToken    *string                 `json:"access_token,omitempty"`
	PasskeyOptions *map[string]interface{} `json:"passkey_options,omitempty"`
	Secret         *string                 `json:"secret,omitempty"`
	TfaType        *LoginResponseTfaType   `json:"tfa_type,omitempty"`
	Type           LoginResponseType       `json:"type"`

	// User 用户响应 payload（snake_case 契约，禁止规范化）。
	User *UserPayload `json:"user,omitempty"`
}

// LoginResponseTfaType defines model for LoginResponse.TfaType.
type LoginResponseTfaType string

// LoginResponseType defines model for LoginResponse.Type.
type LoginResponseType string

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	Id   *string `json:"id,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// OidcAuthRequest defines model for OidcAuthRequest.
type OidcAuthRequest struct {
	DeviceId            *string     `json:"deviceId,omitempty"`
	DeviceInfo          *DeviceInfo `json:"deviceInfo,omitempty"`
	DeviceUuid          *string     `json:"deviceUuid,omitempty"`
	FrontendRedirectUrl *string     `json:"frontendRedirectUrl,omitempty"`
	Provider            string      `json:"provider"`
}

// PasskeyView defines model for PasskeyView.
type PasskeyView struct {
	BackedUp   *bool      `json:"backedUp,omitempty"`
	CreatedAt  *time.Time `json:"createdAt,omitempty"`
	DeviceType *string    `json:"deviceType,omitempty"`
	Guid       string     `json:"guid"`
	Name       *string    `json:"name,omitempty"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	CreatedAt  time.Time `json:"createdAt"`
	DeviceId   *string   `json:"deviceId,omitempty"`
	DeviceName *string   `json:"deviceName,omitempty"`
	DeviceOs   *string   `json:"deviceOs,omitempty"`
	DeviceType *string   `json:"deviceType,omitempty"`
	DeviceUuid *string   `json:"deviceUuid,omitempty"`
	ExpiresAt  time.Time `json:"expiresAt"`
	Jti        string    `json:"jti"`
}

// UpdateMeRequest user 域请求字段为 snake_case（契约，禁止规范化）。
type UpdateMeRequest struct {
	DisplayName *string              `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Note        *string              `json:"note,omitempty"`
}

// UserPayload 用户响应 payload（snake_case 契约，禁止规范化）。
type UserPayload struct {
	Avatar        *string `json:"avatar,omitempty"`
	DisplayName   *string `json:"display_name,omitempty"`
	Email         *string `json:"email,omitempty"`
	Guid          string  `json:"guid"`
	HasPassword   *bool   `json:"has_password,omitempty"`
	IsAdmin       bool    `json:"is_admin"`
	Name          string  `json:"name"`
	Note          *string `json:"note,omitempty"`
	StrategyGuid  *string `json:"strategy_guid,omitempty"`
	TfaEnabled    *bool   `json:"tfa_enabled,omitempty"`
	ThirdAuthType *string `json:"third_auth_type,omitempty"`
	UserGroupGuid *string `json:"user_group_guid,omitempty"`
	Verifier      *string `json:"verifier,omitempty"`
}

// BadRequest NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type BadRequest = Error

// NotFound NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type NotFound = Error

// Unauthorized NestJS 默认错误包络；message 为对象/字符串/字符串数组三种形态之一。
type Unauthorized = Error

// DisableTfaJSONBody defines parameters for DisableTfa.
type DisableTfaJSONBody struct {
	TfaCode string `json:"tfaCode"`
}

// VerifyTfaJSONBody defines parameters for VerifyTfa.
type VerifyTfaJSONBody struct {
	TfaCode string `json:"tfaCode"`
}

// OidcAuthQueryParams defines parameters for OidcAuthQuery.
type OidcAuthQueryParams struct {
	Code string  `form:"code" json:"code"`
	Id   *string `form:"id,omitempty" json:"id,omitempty"`
	Uuid *string `form:"uuid,omitempty" json:"uuid,omitempty"`
}

// OidcCallbackParams defines parameters for OidcCallback.
type OidcCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// PasskeyAuthVerifyJSONBody defines parameters for PasskeyAuthVerify.
type PasskeyAuthVerifyJSONBody struct {
	DeviceInfo *DeviceInfo            `json:"deviceInfo,omitempty"`
	Id         *string                `json:"id,omitempty"`
	Response   map[string]interface{} `json:"response"`
	Secret     string                 `json:"secret"`
	Uuid       *string                `json:"uuid,omitempty"`
}

// PasskeyRegisterVerifyJSONBody defines parameters for PasskeyRegisterVerify.
type PasskeyRegisterVerifyJSONBody struct {
	Name     *string                `json:"name,omitempty"`
	Response map[string]interface{} `json:"response"`
}

// PasskeyTfaToggleJSONBody defines parameters for PasskeyTfaToggle.
type PasskeyTfaToggleJSONBody struct {
	Enabled bool `json:"enabled"`
}

// UploadMyAvatarMultipartBody defines parameters for UploadMyAvatar.
type UploadMyAvatarMultipartBody struct {
	Avatar openapi_types.File `json:"avatar"`
}

// DisableTfaJSONRequestBody defines body for DisableTfa for application/json ContentType.
type DisableTfaJSONRequestBody DisableTfaJSONBody

// VerifyTfaJSONRequestBody defines body for VerifyTfa for application/json ContentType.
type VerifyTfaJSONRequestBody VerifyTfaJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// OidcAuthJSONRequestBody defines body for OidcAuth for application/json ContentType.
type OidcAuthJSONRequestBody = OidcAuthRequest

// PasskeyAuthVerifyJSONRequestBody defines body for PasskeyAuthVerify for application/json ContentType.
type PasskeyAuthVerifyJSONRequestBody PasskeyAuthVerifyJSONBody

// PasskeyRegisterVerifyJSONRequestBody defines body for PasskeyRegisterVerify for application/json ContentType.
type PasskeyRegisterVerifyJSONRequestBody PasskeyRegisterVerifyJSONBody

// PasskeyTfaToggleJSONRequestBody defines body for PasskeyTfaToggle for application/json ContentType.
type PasskeyTfaToggleJSONRequestBody PasskeyTfaToggleJSONBody

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// UploadMyAvatarMultipartRequestBody defines body for UploadMyAvatar for multipart/form-data ContentType.
type UploadMyAvatarMultipartRequestBody UploadMyAvatarMultipartBody

// ChangeMyPasswordJSONRequestBody defines body for ChangeMyPassword for application/json ContentType.
type ChangeMyPasswordJSONRequestBody = ChangePasswordRequest

// AsErrorMessage0 returns the union data inside the Error_Message as a ErrorMessage0
func (t Error_Message) AsErrorMessage0() (ErrorMessage0, error) {
	var body ErrorMessage0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage0 overwrites any union data inside the Error_Message as the provided ErrorMessage0
func (t *Error_Message) FromErrorMessage0(v ErrorMessage0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMessage0 performs a merge with any union data inside the Error_Message, using the provided ErrorMessage0
func (t *Error_Message) MergeErrorMessage0(v ErrorMessage0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMessage1 returns the union data inside the Error_Message as a ErrorMessage1
func (t Error_Message) AsErrorMessage1() (ErrorMessage1, error) {
	var body ErrorMessage1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage1 overwrites any union data inside the Error_Message as the provided ErrorMessage1
func (t *Error_Message) FromErrorMessage1(v ErrorMessage1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMessage1 performs a merge with any union data inside the Error_Message, using the provided ErrorMessage1
func (t *Error_Message) MergeErrorMessage1(v ErrorMessage1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMessage2 returns the union data inside the Error_Message as a ErrorMessage2
func (t Error_Message) AsErrorMessage2() (ErrorMessage2, error) {
	var body ErrorMessage2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage2 overwrites any union data inside the Error_Message as the provided ErrorMessage2
func (t *Error_Message) FromErrorMessage2(v ErrorMessage2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorMessage2 performs a merge with any union data inside the Error_Message, using the provided ErrorMessage2
func (t *Error_Message) MergeErrorMessage2(v ErrorMessage2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Error_Message) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Error_Message) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
